#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Dec 20 17:24:58 CST 2024
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim VGA_test_behav -key {Behavioral:sim_1:Functional:VGA_test} -tclbatch VGA_test.tcl -view /home/user/DLCO/lab12/Computer_System/keyboard_test_behav.wcfg -log simulate.log"
xsim VGA_test_behav -key {Behavioral:sim_1:Functional:VGA_test} -tclbatch VGA_test.tcl -view /home/user/DLCO/lab12/Computer_System/keyboard_test_behav.wcfg -log simulate.log

